apiVersion: apps/v1
kind: Deployment
metadata:
  name: uploader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uploader
  template:
    metadata:
      labels:
        app: uploader
    spec:
      containers:
        - name: uploader
          image: <ACR_NAME>.azurecr.io/uploader:latest
          ports:
            - containerPort: 8000
          env:
            - name: STORAGE_ACCOUNT_NAME
              value: "<STORAGE_ACCOUNT_NAME>"
            - name: RAW_CONTAINER
              value: "rawfiles"
---
apiVersion: v1
kind: Service
metadata:
  name: uploader-service
spec:
  selector:
    app: uploader
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer